## Data Manupilation with Numpy and Pandas in Python 

In [10]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [11]:
#create a list comprising numbers from 0 to 9
L = list(range(10))

In [12]:
#converting integers to string -this style of handling list is known as list comprehension.
#List comprehension offers a versatile way to handle list manipulations tasks easily.We'll learn about them in future tutorials.

c1 = [str(c) for c in L]

c2 = [type(item) for item in L]

print(c1)
print(c2)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
[<class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>]


### Creating Arrays
Numpy arrays are homogeneous in nature i.e they comprise one data type(integer,float,double,etc.) unlike lists.

In [13]:
#creating arrays
np.zeros(10,dtype='int')


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
#creating a 3 row x 5 column matrix
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
#creating a matrix with a predefined value
np.full((3,5),1.23)

array([[1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23]])

In [17]:
#creating an array with a set sequence
#arange(x:başlangıç değeri,y:bitiş değeri,z:aritmetik işlem)
np.arange(0,20,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
#create a 3x3 array with mean 0 and standart deviation 1 in a given dimension
np.random.normal(0,1,(3,3))

array([[ 1.87730879,  1.38573598, -0.15163272],
       [-0.6013399 ,  0.38436587, -0.98265931],
       [-2.12276598,  0.84101719, -0.57455911]])

In [19]:
#create an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [23]:
#set a random seed
np.random.seed(0)

x1 = np.random.randint(10,size=6) #one dimension
x2 = np.random.randint(10,size=(3,4)) #two dimension
x3 = np.random.randint(10,size=(3,4,5)) #three dimension

print('x3 ndim',x3.ndim)
print('x3 ndim',x3.shape)
print('x3 ndim',x3.size)
x3

x3 ndim 3
x3 ndim (3, 4, 5)
x3 ndim 60


array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

### Array Indexing
The important thing to remember is that indexing in python starts at zero

In [24]:
x1 = np.array([4,3,4,4,8,4])
x1

array([4, 3, 4, 4, 8, 4])

In [25]:
x1[0]

4

In [26]:
#get the last value
x1[-1]

4

In [27]:
#get the second last value
x1[-2]

8

In [28]:
#in a multidimensional array,we need to specify row and column index
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [38]:
#1st row and 2nd column value
x2[0,1]

5

In [39]:
#replace value at 0,0 index
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

### Array Silicing
To access multiple or a range of elements from an array

In [40]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
#from start to 4th position
x[:5]

array([0, 1, 2, 3, 4])

In [42]:
#from 4th position to end
x[4:]

array([4, 5, 6, 7, 8, 9])

In [43]:
#from 4th to 6th position
x[4:7]

array([4, 5, 6])

In [44]:
#return elements at even place
x[::2]

array([0, 2, 4, 6, 8])

In [45]:
#return elements from first position step by two
x[1::2]

array([1, 3, 5, 7, 9])

In [46]:
#reverse the array 
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Array Concatenation

In [47]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = [21,21,21]

np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

In [48]:
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [53]:
np.concatenate([grid,grid],axis = 1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Until now,we used the concatenation function of arrays of equal dimension.But,
what if you are required to combine a 2d array with 1d array ?In such sitiations,np.concatenate
might not be the best option to use.Instead,you can use np.vstack or np.hstack to do the task.

In [54]:
x = np.array([3,4,5])
grid = np.array([[1,2,3],[17,18,19]])
np.vstack([x,grid]) #vertical stack ??

array([[ 3,  4,  5],
       [ 1,  2,  3],
       [17, 18, 19]])

In [55]:
z = np.array([[9],[9]])
np.hstack([grid,z]) #horizontal stack ??

array([[ 1,  2,  3,  9],
       [17, 18, 19,  9]])

Also,we can split the arrays based on pre-defined positions.

In [62]:
x = np.arange(10)
x
x1,x2,x3 = np.split(x,[3,6])
print(x1,x2,x3)

[] [] [0 1 2 3 4 5 6 7 8 9]


In [64]:
grid = np.arange(16).reshape((4,4))
grid
upper,lower = np.vsplit(grid,[2])
print(upper,lower)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


### Pandas

In [65]:
#create a data frame -dictionary is used here where keys get converted to column names and values to row 
#values.
data = pd.DataFrame({'Country':['Russia','Colombia','Chile','Equador','Nigeria'],
                     'Rank':[121,40,100,130,11]})
data

Country  Rank
0    Russia   121
1  Colombia    40
2     Chile   100
3   Equador   130
4   Nigeria    11

In [66]:
#We can do a quick analysis of any data set using:
data.describe()

Rank
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

describe() method computes summary statistics of integer/double variables.To get the complete information about the data set,we can use info() function.

In [67]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
Country    5 non-null object
Rank       5 non-null int64
dtypes: int64(1), object(1)
memory usage: 160.0+ bytes


In [76]:
#You can also create DataFrames like this:
np.random.seed(25)
df_obj=DataFrame(np.random.rand(36).reshape((6,6)),index =['row1','row2','row3','row4','row5','row6'],
             columns = ['column1','column2','column3','column4','column5','column6'])
df_obj

column1   column2   column3   column4   column5   column6
row1  0.870124  0.582277  0.278839  0.185911  0.411100  0.117376
row2  0.684969  0.437611  0.556229  0.367080  0.402366  0.113041
row3  0.447031  0.585445  0.161985  0.520719  0.326051  0.699186
row4  0.366395  0.836375  0.481343  0.516502  0.383048  0.997541
row5  0.514244  0.559053  0.034450  0.719930  0.421004  0.436935
row6  0.281701  0.900274  0.669612  0.456069  0.289804  0.525819

In [78]:
data = pd.DataFrame({'group':['a','a','a','b','b','b','c','c','c'],
                    'ounces':[4,3,12,6,7.5,8,3,5,6]})
data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [79]:
#Sorting the data frame by ounces
data.sort_values(by=['ounces'],ascending=True,inplace=False)

group  ounces
1     a     3.0
6     c     3.0
0     a     4.0
7     c     5.0
3     b     6.0
8     c     6.0
4     b     7.5
5     b     8.0
2     a    12.0

In [83]:
data.sort_values(by=['ounces'],ascending=False,inplace=False) #descending

group  ounces
2     a    12.0
5     b     8.0
4     b     7.5
3     b     6.0
8     c     6.0
7     c     5.0
0     a     4.0
1     a     3.0
6     c     3.0

In [89]:
#sorting by multiple columns
data.sort_values(by=['group','ounces'],ascending=[True,False],inplace=False)


group  ounces
2     a    12.0
0     a     4.0
1     a     3.0
5     b     8.0
4     b     7.5
3     b     6.0
8     c     6.0
7     c     5.0
6     c     3.0

In [90]:
#creating data with duplicated rows
data = pd.DataFrame({'k1':['one']*3 + ['two']*4,'k2':[3,2,1,3,3,4,4]})
data

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [91]:
#sort values
data.sort_values(by='k2')

k1  k2
2  one   1
1  one   2
0  one   3
3  two   3
4  two   3
5  two   4
6  two   4

In [92]:
#remove duplicates
data.drop_duplicates()

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
5  two   4

In [93]:
#we can also remove duplicates based on a particular column.
data.drop_duplicates(subset='k1')

k1  k2
0  one   3
3  two   3

To categorize rows based on a predefined criteria.

In [94]:
data = pd.DataFrame({'food':['bacon','pulled pork','bacon','Pastrami','corned beef','Bacon','pastrami',
                            'honey ham','nova lox'],
                     'ounces':[4,3,12,6,7.5,8.,3,5,6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [111]:
meat_to_animal = {
    'bacon':'pig',
    'pulled pork':'pig',
    'pastrami':'cow',
    'corned beef':'cow',
    'honey ham':'pig',
    'nova lox':'salmon'
}

def meat_2_animal(series):
    if series['food'] == 'bacon':
        return 'pig'
    elif series['food'] == 'pulled pork':
        return 'pig'
    elif series['food'] == 'pastrami':
        return 'cow'
    elif series['food'] == 'corned beef':
        return 'cow'
    elif series['food'] == 'honey ham':
        return 'pig'
    else:
        return 'salmon'

#create a new variable
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
data
    

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [112]:
#another way of doing it is: convert the food values to the lower case and apply the function
lower = lambda x: x.lower()
data['food'] = data['food'].apply(lower)
data['animal2'] = data.apply(meat_2_animal, axis='columns')
data

food  ounces  animal animal2
0        bacon     4.0     pig     pig
1  pulled pork     3.0     pig     pig
2        bacon    12.0     pig     pig
3     pastrami     6.0     cow     cow
4  corned beef     7.5     cow     cow
5        bacon     8.0     pig     pig
6     pastrami     3.0     cow     cow
7    honey ham     5.0     pig     pig
8     nova lox     6.0  salmon  salmon

Another way to create a new variable is by using the assign function. With this tutorial, as you keep discovering the new functions, you'll realize how powerful pandas is.

In [113]:
data.assign(new_variable = data['ounces']*10)

food  ounces  animal animal2  new_variable
0        bacon     4.0     pig     pig          40.0
1  pulled pork     3.0     pig     pig          30.0
2        bacon    12.0     pig     pig         120.0
3     pastrami     6.0     cow     cow          60.0
4  corned beef     7.5     cow     cow          75.0
5        bacon     8.0     pig     pig          80.0
6     pastrami     3.0     cow     cow          30.0
7    honey ham     5.0     pig     pig          50.0
8     nova lox     6.0  salmon  salmon          60.0

In [114]:
data.drop('animal2',axis='columns',inplace=True)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

#### Finding and replacing missing values,outliers etc.

In [120]:
#Series function from pandas are used to create arrays
data = pd.Series([1.,-999.,2.,-999.,-1000.,3.])
data

#You can put NaN values by manually
missing = np.nan
data1 = pd.Series([1,missing,54,23,3,missing,42,1231,34,missing,missing])
data1


0        1.0
1        NaN
2       54.0
3       23.0
4        3.0
5        NaN
6       42.0
7     1231.0
8       34.0
9        NaN
10       NaN
dtype: float64

In [121]:
#replace -999 with NaN values
data.replace(-999,np.nan,inplace=True)
data

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [122]:
#We can also replace multiple values at once.
data = pd.Series([1.,-999.,2.,-999.,-1000.,3.])
data.replace([-999,-1000],np.nan,inplace=True)
data

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

#### Renaming column and axis names(rows)

In [123]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),index=['Ohio','Colarado','New York'],
                   columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colarado    4    5      6     7
New York    8    9     10    11

In [125]:
#Using rename function
data.rename(index={'Ohio':'SanF'},columns={'one':'one_p','two':'two_p'},inplace=True)
data

one_p  two_p  three  four
SanF          0      1      2     3
Colarado      4      5      6     7
New York      8      9     10    11

In [126]:
#You can also use string functions
data.rename(index=str.upper,columns=str.title,inplace=True)
data

One_P  Two_P  Three  Four
SANF          0      1      2     3
COLARADO      4      5      6     7
NEW YORK      8      9     10    11

#### Catogorizing continuous variables

In [127]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]

#We'll divide the ages into bins such as 18-25,26-35,36-60 and 60 and above.
#'(' means the value is included in the bin , '[' means the value is exluded.

bins = [18,25,35,60,100]
cats = pd.cut(ages,bins)
cats


[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [128]:
#To include the right bin value:
pd.cut(ages,bins,right = False)


[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [158]:
#Checking how many observations fall under each bin:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [159]:
#We can pass a unique name to each label
bin_names = ['Youth','YoungAdult','MiddleAge','Senior']
new_cats = pd.cut(ages,bins,labels=bin_names)
pd.value_counts(new_cats)

Youth         5
MiddleAge     3
YoungAdult    3
Senior        1
dtype: int64

In [160]:
#We can also calculate their cumulative sum
pd.value_counts(new_cats).cumsum()

Youth          5
MiddleAge      8
YoungAdult    11
Senior        12
dtype: int64

#### Grouping data and creating pivots

In [161]:
df = pd.DataFrame({'key1': ['a','a','b','b','a'],
                   'key2': ['one','two','one','two','one'],
                   'data1':np.random.randn(5),
                   'data2':np.random.randn(5)})
df

key1 key2     data1     data2
0    a  one  1.607671 -0.633439
1    a  two  0.388292  0.246622
2    b  one  0.399732 -1.939546
3    b  two  0.405477  0.114060
4    a  one  0.217002 -1.885341

In [162]:
#calculate the mean of data1 column by key1
grouped = df['data1'].groupby(df['key1'])
grouped.mean()

key1
a    0.737655
b    0.402604
Name: data1, dtype: float64

In [169]:
dates = pd.date_range('20130101',periods=6)
df=pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
df


A         B         C         D
2013-01-01  0.243080 -0.705481  0.364628 -0.502952
2013-01-02 -0.225752 -0.565538  0.103395  2.018408
2013-01-03  1.094248  1.662434 -0.627453  1.621200
2013-01-04  1.178133 -0.374879 -0.544329  0.287761
2013-01-05 -0.205820  1.189988  0.728927 -0.222040
2013-01-06 -1.622706  0.312541 -1.160421  0.313560

In [170]:
#get first n rows from the data frame
df[:3]

A         B         C         D
2013-01-01  0.243080 -0.705481  0.364628 -0.502952
2013-01-02 -0.225752 -0.565538  0.103395  2.018408
2013-01-03  1.094248  1.662434 -0.627453  1.621200

In [171]:
#get last n rows from the data frame
df[3:]

A         B         C         D
2013-01-04  1.178133 -0.374879 -0.544329  0.287761
2013-01-05 -0.205820  1.189988  0.728927 -0.222040
2013-01-06 -1.622706  0.312541 -1.160421  0.313560

In [172]:
#slice based on date range
df['20130101':'20130104']

A         B         C         D
2013-01-01  0.243080 -0.705481  0.364628 -0.502952
2013-01-02 -0.225752 -0.565538  0.103395  2.018408
2013-01-03  1.094248  1.662434 -0.627453  1.621200
2013-01-04  1.178133 -0.374879 -0.544329  0.287761

In [173]:
#slicing based on column names
df.loc[:,['A','B']]

A         B
2013-01-01  0.243080 -0.705481
2013-01-02 -0.225752 -0.565538
2013-01-03  1.094248  1.662434
2013-01-04  1.178133 -0.374879
2013-01-05 -0.205820  1.189988
2013-01-06 -1.622706  0.312541

In [174]:
#slicing based on both row index labels and column names
df.loc['20130102':'20130103',['A','B']]

A         B
2013-01-02 -0.225752 -0.565538
2013-01-03  1.094248  1.662434

In [176]:
#slicing based on index of column
df.iloc[3] #returns 4th row(index is 3rd)

A    1.178133
B   -0.374879
C   -0.544329
D    0.287761
Name: 2013-01-04 00:00:00, dtype: float64

In [179]:
#returns a specific range of rows
df.iloc[2:4,0:2]

A         B
2013-01-03  1.094248  1.662434
2013-01-04  1.178133 -0.374879

In [180]:
#returns specific rows and columns using lists containing column or row indexes
df.iloc[[1,5],[0,2]]

A         C
2013-01-02 -0.225752  0.103395
2013-01-06 -1.622706 -1.160421

#### Boolean indexing based on column values.This helps in filtering a data set based on a pre-defined condition

In [187]:
df[df.A > 1] #???????????????

A         B         C         D
2013-01-03  1.094248  1.662434 -0.627453  1.621200
2013-01-04  1.178133 -0.374879 -0.544329  0.287761

In [191]:
#copying the data set
df2 = df.copy()
df2['E'] = ['one','one','two','three','four','three']
df2['G'] = ['Alpha','Bravo','Charlie','Delta','Echo','Golf']
df2

A         B         C         D      E        G
2013-01-01  0.243080 -0.705481  0.364628 -0.502952    one    Alpha
2013-01-02 -0.225752 -0.565538  0.103395  2.018408    one    Bravo
2013-01-03  1.094248  1.662434 -0.627453  1.621200    two  Charlie
2013-01-04  1.178133 -0.374879 -0.544329  0.287761  three    Delta
2013-01-05 -0.205820  1.189988  0.728927 -0.222040   four     Echo
2013-01-06 -1.622706  0.312541 -1.160421  0.313560  three     Golf

In [198]:
#select rows based on column values
df2[df2['E'].isin(['two','four'])]

A         B         C        D     E
2013-01-03  1.094248  1.662434 -0.627453  1.62120   two
2013-01-05 -0.205820  1.189988  0.728927 -0.22204  four

In [200]:
#select all rows except those with two and four
df2[~df2['E'].isin(['two','four'])]


A         B         C         D      E
2013-01-01  0.243080 -0.705481  0.364628 -0.502952    one
2013-01-02 -0.225752 -0.565538  0.103395  2.018408    one
2013-01-04  1.178133 -0.374879 -0.544329  0.287761  three
2013-01-06 -1.622706  0.312541 -1.160421  0.313560  three

#### Query method to select columns based on a criterion.

In [201]:
#list all column where A is greater than C
df.query('A > C')

A         B         C         D
2013-01-03  1.094248  1.662434 -0.627453  1.621200
2013-01-04  1.178133 -0.374879 -0.544329  0.287761

In [202]:
#using OR condition
df.query('A < B | C > A')

A         B         C         D
2013-01-01  0.243080 -0.705481  0.364628 -0.502952
2013-01-02 -0.225752 -0.565538  0.103395  2.018408
2013-01-03  1.094248  1.662434 -0.627453  1.621200
2013-01-05 -0.205820  1.189988  0.728927 -0.222040
2013-01-06 -1.622706  0.312541 -1.160421  0.313560