In [6]:
import numpy as np
import pandas as pd


pd.Series([1,2,3,4])


0    1
1    2
2    3
3    4
dtype: int64

In [7]:
seri = pd.Series([1,2,3,4])
type(seri)

pandas.core.series.Series

In [8]:
dir(seri)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_SLICEMAP',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_prepare__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__bytes__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 

In [9]:
seri.axes

[RangeIndex(start=0, stop=4, step=1)]

In [10]:
seri.values

array([1, 2, 3, 4], dtype=int64)

In [11]:
seri.head(2)

0    1
1    2
dtype: int64

In [12]:
seri[0:3]

0    1
1    2
2    3
dtype: int64

In [13]:
seri.tail(2)

2    3
3    4
dtype: int64

In [14]:
a = np.array([1,2,3,566,88])

In [15]:
seri = pd.Series(a)
seri

0      1
1      2
2      3
3    566
4     88
dtype: int32

In [16]:
seri.index

RangeIndex(start=0, stop=5, step=1)

In [17]:
pd.Series([1,5,0.9,34],index= [1,3,5,7])

1     1.0
3     5.0
5     0.9
7    34.0
dtype: float64

In [18]:
pd.Series([1,5,0.9,34],index= ['a','b','c','d'])

a     1.0
b     5.0
c     0.9
d    34.0
dtype: float64

In [19]:
sozluk = {"red":10,"loj":11,"cart":12}
sozluk

{'red': 10, 'loj': 11, 'cart': 12}

In [20]:
pd.Series(sozluk)

red     10
loj     11
cart    12
dtype: int64

In [21]:
seri["loj":"cart"]

TypeError: cannot do slice indexing on <class 'pandas.core.indexes.range.RangeIndex'> with these indexers [loj] of <class 'str'>

Serilerde Eleman İşlemleri

In [22]:
seri = pd.Series([121,200,150,99],index=["reg","loj","cart","rf"])
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [23]:
seri[(seri > 125) & (seri < 200)]

cart    150
dtype: int64

In [24]:
data = pd.Series(['a','b','c'],index = [1,3,5])
data

1    a
3    b
5    c
dtype: object

In [25]:
data[0]

KeyError: 0

In [26]:
data[1]

'a'

In [27]:
#loc label based indexing(tanımlandığı şekliyle index yakalamak)

In [28]:
data

1    a
3    b
5    c
dtype: object

In [29]:
data.loc[0:2]

1    a
dtype: object

In [30]:
#iloc positional indexing(indexi 0layarak yakalamak)
data.iloc[0]

'a'

Pandas DataFrame

In [31]:
l = [1,4,577,343]
l

[1, 4, 577, 343]

In [32]:
pd.DataFrame(l,columns=['degisken-ismi'])

degisken-ismi
0              1
1              4
2            577
3            343

In [33]:
a = np.random.randint(0,100,(2,3,3))
a

array([[[85, 57, 98],
        [92, 80, 80],
        [93, 38, 49]],

       [[63, 83, 16],
        [ 9, 86, 98],
        [60, 55,  0]]])

In [34]:
b = np.array([[[21, 73, 95],
        [ 9, 27, 29],
        [23, 81, 71]]])
b


array([[[21, 73, 95],
        [ 9, 27, 29],
        [23, 81, 71]]])

In [35]:
x = np.concatenate([a,b])
x
y = a[0,0]
y

array([85, 57, 98])

In [36]:
np.where(y in x)

(array([0], dtype=int64),)

In [37]:
x

array([[[85, 57, 98],
        [92, 80, 80],
        [93, 38, 49]],

       [[63, 83, 16],
        [ 9, 86, 98],
        [60, 55,  0]],

       [[21, 73, 95],
        [ 9, 27, 29],
        [23, 81, 71]]])

In [38]:
x[0]

array([[85, 57, 98],
       [92, 80, 80],
       [93, 38, 49]])

In [39]:
x[(x == [y])]

array([85, 57, 98, 98])

In [40]:
np.argwhere(x==y)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 2],
       [1, 1, 2]], dtype=int64)

In [41]:
z = np.array([21,73,95])
g = np.array([1,2,5,32,32,12,2,5,21,73,95,32,1,2])
x[(x==z)]

array([21, 73, 95])

In [42]:
def first_subarray(full_array, sub_array):
    n = len(full_array)
    k = len(sub_array)
    matches = np.argwhere([np.all(full_array[start_ix:start_ix+k] == sub_array) 
                   for start_ix in range(0, n-k+1)])
    return matches[0]

for i in range(0,len(g)):
    first_subarray(g,i)

TypeError: object of type 'int' has no len()

In [43]:
x[0]

array([[85, 57, 98],
       [92, 80, 80],
       [93, 38, 49]])

In [44]:
for i in range(0,len(z)):
    if np.any(x[:,:,i] == z[i]):
        print(z[i])

21
73
95


In [45]:
def function_1(seq, sub):
    # direct comparison
    seq = list(seq)
    sub = list(sub)
    return [i for i in range(len(seq) - len(sub)) if seq[i:i+len(sub)] == sub]

function_1(x,z)

[]

In [46]:
def function_2(seq, sub):
    # Jamie's solution
    target = np.dot(sub, sub)
    candidates = np.where(np.correlate(seq, sub, mode='valid') == target)[0]
    check = candidates[:, np.newaxis] + np.arange(len(sub))
    mask = np.all((np.take(seq, check) == sub), axis=-1)
    return candidates[mask]

function_2(x,z)

ValueError: object too deep for desired array

In [47]:
def function_3(seq, sub):
    # HYRY solution
    return seq.tostring().index(sub.tostring())//seq.itemsize

function_3(x,z)

18

In [48]:
result = np.logical_and(x[:,:,0]==z[0],x[:,:,1]==z[1],x[:,:,2]==z[2])

np.where(result)

(array([2], dtype=int64), array([0], dtype=int64))

In [49]:
res = np.where(x[np.logical_and(x[:,:,0]==z[0],x[:,:,1]==z[1],x[:,:,2]==z[2])])
a_res = res[0]
b_res = res[1]

np.vstack([a_res,b_res])

array([[0, 0, 0],
       [0, 1, 2]], dtype=int64)

In [50]:
np.where(np.logical_and(x[:,:,0]==z[0],x[:,:,1]==z[1],x[:,:,2]==z[2]))

(array([2], dtype=int64), array([0], dtype=int64))

In [51]:
res_x=np.where(x > 25)[0]
res_y=np.where(x > 25)[1]
res_z=np.where(x > 25)[2]

np.hstack([res_x,res_y,res_z])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 0,
       0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 1, 2, 0, 1, 1, 2, 1, 2, 1, 2],
      dtype=int64)

In [52]:
np.where(np.logical_and(x[:,:,0] == 21,x[:,:,1]==73))

(array([2], dtype=int64), array([0], dtype=int64))

In [53]:
x[2,0,0]

21

In [54]:
z2=np.array([[21, 73, 95],
        [ 9, 27, 29],
        [23, 81, 71]])
z2

array([[21, 73, 95],
       [ 9, 27, 29],
       [23, 81, 71]])

In [55]:
zx1 = np.array([21,73,95])
zx2 = np.array([9,27,29])
zx3 = np.array([23,81,71])

q1 = x[np.logical_and(x[:,:,0]==zx1[0],x[:,:,1]==zx1[1],x[:,:,2]==zx1[2])]
q2 = x[np.logical_and(x[:,:,0]==zx2[0],x[:,:,1]==zx2[1],x[:,:,2]==zx2[2])]
q3 = x[np.logical_and(x[:,:,0]==zx3[0],x[:,:,1]==zx3[1],x[:,:,2]==zx3[2])]

qx = x[np.logical_and(x[:,0]==z2[0],x[:,1]==z2[1],x[:,2]==z2[2])]
qx

#qy = x[np.logical_and(x[:,0]==z2[:,0],x[:,1]==z2[:,1],x[:,2]==z2[:,2])]
#qy



array([[21, 73, 95],
       [ 9, 27, 29],
       [23, 81, 71]])

In [56]:
x[:,2]

array([[93, 38, 49],
       [60, 55,  0],
       [23, 81, 71]])

In [57]:
x5 = x
x6 = np.array([[[z]]])

In [58]:
x6


array([[[[21, 73, 95]]]])

In [59]:
x7 = np.array([z])

In [60]:
x7


array([[21, 73, 95]])

In [61]:
x8 = np.array([[z]])
x8

array([[[21, 73, 95]]])

In [62]:
x8 = np.array([[[21,73,95],
               [9,27,29],
               [23,81,71]
               ]])
x8

array([[[21, 73, 95],
        [ 9, 27, 29],
        [23, 81, 71]]])

In [63]:
x5

array([[[85, 57, 98],
        [92, 80, 80],
        [93, 38, 49]],

       [[63, 83, 16],
        [ 9, 86, 98],
        [60, 55,  0]],

       [[21, 73, 95],
        [ 9, 27, 29],
        [23, 81, 71]]])

In [64]:
import numpy as np
x10 = np.concatenate((x5,x8),axis=0)

In [65]:
x10

array([[[85, 57, 98],
        [92, 80, 80],
        [93, 38, 49]],

       [[63, 83, 16],
        [ 9, 86, 98],
        [60, 55,  0]],

       [[21, 73, 95],
        [ 9, 27, 29],
        [23, 81, 71]],

       [[21, 73, 95],
        [ 9, 27, 29],
        [23, 81, 71]]])

In [71]:
x20 = x10[3,0:2]
x20

array([[21, 73, 95],
       [ 9, 27, 29]])

In [82]:
x10[0,0:2]
x10[:,0:2]

array([[[85, 57, 98],
        [92, 80, 80]],

       [[63, 83, 16],
        [ 9, 86, 98]],

       [[21, 73, 95],
        [ 9, 27, 29]],

       [[21, 73, 95],
        [ 9, 27, 29]]])

In [68]:
np.equal(x10[3,0:2],x10[0,0:2])

array([[False, False, False],
       [False, False, False]])

In [80]:
x21 = np.array([[21,73,95],[9,27,29]])
x21

array([[21, 73, 95],
       [ 9, 27, 29]])

In [107]:
x50 = x10[(np.logical_and(x10[:,:,0]==21,x10[:,:,1]==73,x10[:,:,2]==95))]
x51 = x10[(np.logical_and(x10[:,:,0]==21,x10[:,:,1]==73,x10[:,:,2]==95))]
#x10[(x10[:,0:2]==([[21,73,95],[9,27,29]]]))]
np.where(x10[:,0:2]==x21)
#x10[x10[:,0:2]==x22]
x10[:,0:2][2]

array([[21, 73, 95],
       [ 9, 27, 29]])

In [91]:
x10.ndim

3

In [92]:
x21.ndim

2

In [93]:
x22 = np.array([x21])

In [94]:
x22

array([[[21, 73, 95],
        [ 9, 27, 29]]])

In [95]:
x22.ndim

3

In [232]:
x10[np.where(x10[:,:2]==x21)]

array([ 9, 21, 73, 95,  9, 27, 29, 21, 73, 95,  9, 27, 29])

In [116]:
array([[[85, 57, 98],
        [92, 80, 80],
        [93, 38, 49]],

       [[63, 83, 16],
        [ 9, 86, 98],
        [60, 55,  0]],

       [[21, 73, 95],
        [ 9, 27, 29],
        [23, 81, 71]],

       [[21, 73, 95],
        [ 9, 27, 29],
        [23, 81, 71]]])

NameError: name 'array' is not defined

In [120]:
x10[:,0:2][2]

array([[21, 73, 95],
       [ 9, 27, 29]])

In [125]:
 x10[(np.logical_and(x10[:,:,0]==21,x10[:,:,1]==73,x10[:,:,2]==95))]

array([[21, 73, 95],
       [21, 73, 95]])

In [193]:
x10[x10==np.array([21,73,95])]
z10 = np.array([21,73,95])
z11 = np.array([9,27,29])
x10[np.where(np.logical_and(np.equal(x10[:,0],z10),np.equal(x10[:,1],z11)))]
np.where(np.logical_and(np.equal(x10[:,0],z10),np.equal(x10[:,1],z11)))

(array([2, 2, 2, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [136]:
z10

array([21, 73, 95])

In [149]:
a_ = np.array([23,81,71])


False

In [289]:
ap =np.where(np.logical_and(x10[:,:,0]==21,x10[:,:,1]==73,x10[:,:,2]==95))
pa=np.where(np.logical_and(x10[:,:,0]==9,x10[:,:,1]==27,x10[:,:,2]==29))
pa
ap
np.where(x10[np.where(x10[:,:,0]==9)])
al=np.where(x10[:,:,:]==z10)
pa=np.where(np.any(x10[:,:,:]==z10[:]))
pa
np.where(np.logical_and(x10[:,:,0]==9,x10[:,:,1]==27,x10[:,:,2]==29))
#npre(np.logical_and(x10[:,:,:1]==9,x10[:,:,:2]==27,x10[:,:]==29))
#x10[:,:2]
#np.where(x10[:,:,0:1]==9)
#np.where(x10[:,:,1:2]==27)
#np.where(x10[:,:,2:3]==29)
#p.where(np.logical_and(x10[:,:,:1]==9,x10[:,:,:2]==27,x10[:,:==29))
np.where(np.logical_and(x10[:,:,0]==9,x10[:,:,1]==27,x10[:,:,2]==29))
x10[:1,:1,:]
np.where(np.logical_and(x10[:,0,:]==9,x10[:,1,:]==23))
#10[:,0]
#10[:,1]

(array([], dtype=int64), array([], dtype=int64))